import type{Article,CommunityPost,Species}from '@/types/content'
export const species:Species[]=[
{slug:'ball-python',commonName:'Ball Python',scientificName:'Python regius',category:'Snakes',careLevel:'Beginner',lifespan:'20–30 years',adultSize:'90–150 cm',temperature:'26–33°C',humidity:'60–80%',feeding:'Appropriately sized rodents every 7–14 days',habitat:'Secure terrestrial vivarium with warm and cool hides',morphs:'Thousands of recognized color and pattern combinations',image:'https://images.unsplash.com/photo-1531386151447-fd76ad50012f?auto=format&fit=crop&w=1200&q=85'},
{slug:'crested-gecko',commonName:'Crested Gecko',scientificName:'Correlophus ciliatus',category:'Lizards',careLevel:'Beginner',lifespan:'15–20 years',adultSize:'18–23 cm',temperature:'22–26°C',humidity:'50–80%',feeding:'Complete crested gecko diet with occasional insects',habitat:'Tall planted enclosure with climbing structure',morphs:'Flame, harlequin, pinstripe, dalmatian and more',image:'https://images.unsplash.com/photo-1585095595205-e68428a9e205?auto=format&fit=crop&w=1200&q=85'},
{slug:'axolotl',commonName:'Axolotl',scientificName:'Ambystoma mexicanum',category:'Amphibians',careLevel:'Intermediate',lifespan:'10–15 years',adultSize:'23–30 cm',temperature:'16–20°C',humidity:'Aquatic',feeding:'Earthworms and quality aquatic carnivore pellets',habitat:'Cool, cycled aquarium with low flow and hides',morphs:'Wild, leucistic, golden albino and melanoid',image:'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=1200&q=85'},
{slug:'blue-tongued-skink',commonName:'Blue-tongued Skink',scientificName:'Tiliqua scincoides',category:'Lizards',careLevel:'Intermediate',lifespan:'15–20 years',adultSize:'45–60 cm',temperature:'24–38°C',humidity:'40–60%',feeding:'Varied omnivorous diet with correct calcium balance',habitat:'Wide terrestrial enclosure with deep substrate',morphs:'Classic, albino, hypermelanistic and locality forms',image:'https://images.unsplash.com/photo-1617691763432-8b45e6748b71?auto=format&fit=crop&w=1200&q=85'}]
export const articles:Article[]=[
{id:'bioactive',title:'Build a bioactive enclosure that truly thrives',category:'Husbandry',tags:['bioactive','substrate'],excerpt:'A practical system for drainage, substrate, plants, and cleanup crews.',readTime:'9 min',image:'https://images.unsplash.com/photo-1534294228306-bd54eb9a7ba8?auto=format&fit=crop&w=900&q=85'},
{id:'lighting',title:'A keeper’s guide to reptile lighting',category:'Equipment',tags:['UVB','lighting'],excerpt:'Understand UV index, heat, distance, and safe lamp placement.',readTime:'7 min',image:'https://images.unsplash.com/photo-1615809599991-7b5b51c829ba?auto=format&fit=crop&w=900&q=85'},
{id:'feeding',title:'When appetite tells a deeper story',category:'Feeding',tags:['nutrition','health'],excerpt:'Use body condition and behavior—not the calendar alone.',readTime:'6 min',image:'https://images.unsplash.com/photo-1531877264583-a58acd888a97?auto=format&fit=crop&w=900&q=85'}]
export const posts:CommunityPost[]=[
{id:'1',title:'First bioactive build — what would you change?',category:'Husbandry',author:'leafandscale',votes:142,replies:28,species:'Crested Gecko',createdAt:'18m'},
{id:'2',title:'Is this normal pre-shed behavior for a juvenile?',category:'Questions',author:'nocturnal_nora',votes:89,replies:17,species:'Ball Python',createdAt:'42m'},
{id:'3',title:'My rescued blue tongue finally took food!',category:'Showcase',author:'mosskeeper',votes:327,replies:44,species:'Blue-tongued Skink',createdAt:'1h'}]
