import type{Article,CommunityPost,Species}from '@/types/content'
const images={ballPython:'https://commons.wikimedia.org/wiki/Special:FilePath/Python%20regius%20-%20ball%20python.jpg?width=1400',crestedGecko:'https://commons.wikimedia.org/wiki/Special:FilePath/Gekon%20orz%C4%99siony%2C%20Correlophus%20ciliatus.jpg?width=1400',axolotl:'https://commons.wikimedia.org/wiki/Special:FilePath/Ambystoma%20mexicanum%20-%20Aksolotli%2C%20Mexican%20axolotl%20C%20IMG%203700.JPG?width=1400',blueTongue:'https://commons.wikimedia.org/wiki/Special:FilePath/Tiliqua%20scincoides%20%28White%2C%201790%29.jpg?width=1400'} as const;
export const species:Species[]=[
{slug:'ball-python',commonName:'Ball Python',scientificName:'Python regius',category:'Snakes',careLevel:'Beginner',lifespan:'20–30 years',adultSize:'90–150 cm',temperature:'26–33°C',humidity:'60–80%',feeding:'Appropriately sized rodents every 7–14 days',habitat:'Secure terrestrial vivarium with warm and cool hides',morphs:'Thousands of recognized color and pattern combinations',image:images.ballPython,imageAlt:'A ball python (Python regius) resting on a branch'},
{slug:'crested-gecko',commonName:'Crested Gecko',scientificName:'Correlophus ciliatus',category:'Lizards',careLevel:'Beginner',lifespan:'15–20 years',adultSize:'18–23 cm',temperature:'22–26°C',humidity:'50–80%',feeding:'Complete crested gecko diet with occasional insects',habitat:'Tall planted enclosure with climbing structure',morphs:'Flame, harlequin, pinstripe, dalmatian and more',image:images.crestedGecko,imageAlt:'A crested gecko (Correlophus ciliatus) in profile'},
{slug:'axolotl',commonName:'Axolotl',scientificName:'Ambystoma mexicanum',category:'Amphibians',careLevel:'Intermediate',lifespan:'10–15 years',adultSize:'23–30 cm',temperature:'16–20°C',humidity:'Aquatic',feeding:'Earthworms and quality aquatic carnivore pellets',habitat:'Cool, cycled aquarium with low flow and hides',morphs:'Wild, leucistic, golden albino and melanoid',image:images.axolotl,imageAlt:'A Mexican axolotl (Ambystoma mexicanum) underwater'},
{slug:'blue-tongued-skink',commonName:'Blue-tongued Skink',scientificName:'Tiliqua scincoides',category:'Lizards',careLevel:'Intermediate',lifespan:'15–20 years',adultSize:'45–60 cm',temperature:'24–38°C',humidity:'40–60%',feeding:'Varied omnivorous diet with correct calcium balance',habitat:'Wide terrestrial enclosure with deep substrate',morphs:'Classic, albino, hypermelanistic and locality forms',image:images.blueTongue,imageAlt:'An eastern blue-tongued skink (Tiliqua scincoides)'}]
export const articles:Article[]=[
{id:'bioactive',title:'Build a bioactive enclosure that truly thrives',category:'Husbandry',tags:['bioactive','substrate'],excerpt:'A practical system for drainage, substrate, plants, and cleanup crews.',readTime:'9 min read',author:'Dr. Maya Chen',image:images.crestedGecko,imageAlt:'Crested gecko, a species often kept in planted bioactive enclosures'},
{id:'lighting',title:'A keeper’s guide to reptile lighting',category:'Equipment',tags:['UVB','lighting'],excerpt:'Understand UV index, heat, distance, and safe lamp placement.',readTime:'7 min read',author:'Eli Morgan',image:images.blueTongue,imageAlt:'Blue-tongued skink, a basking reptile that benefits from appropriate lighting'},
{id:'feeding',title:'When appetite tells a deeper story',category:'Feeding',tags:['nutrition','health'],excerpt:'Use body condition and behavior—not the calendar alone.',readTime:'6 min read',author:'Dr. Nina Patel',image:images.ballPython,imageAlt:'Ball python used to illustrate reptile feeding and body condition'}]
export const posts:CommunityPost[]=[
{id:'1',title:'First bioactive build — what would you change?',category:'Husbandry',author:'leafandscale',votes:142,replies:28,species:'Crested Gecko',createdAt:'18m',pinned:true},
{id:'2',title:'Is this normal pre-shed behavior for a juvenile?',category:'Questions',author:'nocturnal_nora',votes:89,replies:17,species:'Ball Python',createdAt:'42m'},
{id:'3',title:'My rescued blue tongue finally took food!',category:'Showcase',author:'mosskeeper',votes:327,replies:44,species:'Blue-tongued Skink',createdAt:'1h'}]
